[package]
name = "rust_lib_starter_sample"
version = "0.0.1-beta.4"
edition = "2018"
description = "Library sample."
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
